import type { NextPage } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'

import wordlist, { Word } from '../data/wordlist'

var shuffle = <T extends any>(arr: T[]): T[] => {
  const len = arr.length
  const remaining: T[] = [...arr]
  const shuffled: T[] = []
  while (shuffled.length < len) {
    let i = Math.floor(Math.random() * remaining.length)
    let item = remaining.splice(i, 1)[0]
    shuffled.push(item)
  }
  return shuffled
}

const Container = ({ children }: { children: React.ReactNode }) => (
  <div className="flex-center h-screen w-screen flex-col">{children}</div>
)

interface ButtonProps {
  onClick: () => void
  children?: React.ReactNode
}
const Button = ({ onClick, children }: ButtonProps) => {
  return (
    <button
      className="rounded-full bg-gray-200 px-2 py-1"
      onClick={() => onClick()}
    >
      {children}
    </button>
  )
}

const WordHanzi = ({ word }: { word?: Word }) => (
  <div className="text-9xl">{word ? word.hanzi : ':)'}</div>
)

const WordInfo = ({ word }: { word?: Word }) =>
  word ? (
    <div className="inline-block h-full overflow-y-scroll text-left">
      <p>
        <span className="bold">pinyin:</span> {word?.pinyin}
      </p>
      <p>
        <span className="bold">{word.type}</span> {word.definition}
      </p>
    </div>
  ) : null

interface CardProps {
  word: Word
  markCorrect: () => void
  markIncorrect: () => void
}
const Card = ({ word, markCorrect, markIncorrect }: CardProps) => {
  const defaultDur = 500

  const [isFlipped, setIsFlipped] = useState(false)
  const [isFlipping, setIsFlipping] = useState(false)
  const [flipDur, setFlipDur] = useState(defaultDur)

  const [frontContent, setFrontContent] = useState(<WordHanzi word={word} />)
  const [backContent, setBackContent] = useState(<WordInfo word={word} />)

  const flip = () => {
    if (isFlipping) return
    setIsFlipped(show => !show)
    if (flipDur > 0) {
      setIsFlipping(true)
      setTimeout(() => {
        setIsFlipping(false)
      }, flipDur)
    }
  }

  /**
   * handles the answer
   */
  const handleAnswer = (answer: () => void) => {
    if (isFlipping) return
    if (!isFlipped) {
      // if card is front-side up, secretly flip it first
      setBackContent(frontContent)
      setFlipDur(0)
      setIsFlipped(true)
    }

    // handle the answer and get a new word
    answer()
  }

  /** reset the card to its initial state whenever it recieves a new word */
  useEffect(() => {
    setFrontContent(<WordHanzi word={word} />)
    setIsFlipped(false)
    setFlipDur(defaultDur)
    setIsFlipping(true)
    setTimeout(() => {
      setBackContent(<WordInfo word={word} />)
      setIsFlipping(false)
    }, defaultDur)
  }, [word])

  return (
    <div className="context-3d">
      <button
        className={`flex-center flippable ${
          isFlipped ? 'flippable--flipped' : ''
        } rounded-2xl border-4 border-slate-500/10 p-4 text-slate-800`}
        style={{
          transitionDuration: flipDur.toString() + 'ms',
        }}
        onClick={() => flip()}
      >
        <h1 className="flippable__front">{frontContent}</h1>
        <div className="flippable__back absolute inset-4 text-center">
          {backContent}
        </div>
      </button>
      <div className="mt-4 flex justify-between space-x-2">
        <Button onClick={() => handleAnswer(markCorrect)}>Correct</Button>
        <Button onClick={() => handleAnswer(markIncorrect)}>Incorrect</Button>
      </div>
    </div>
  )
}

const Home: NextPage = () => {
  const [words, setWords] = useState(wordlist)
  const [completed, setCompleted] = useState<Word[]>([])
  const currentWord = words[0]

  const resetFlashcards = () => {
    setWords(shuffle(wordlist))
    setCompleted([])
  }
  useEffect(resetFlashcards, [])

  const markCorrect = () => {
    setCompleted(completed => completed.concat(currentWord))
    setWords(words => words.slice(1))
  }
  const markIncorrect = () => {
    setWords(words => words.slice(1).concat(currentWord))
  }

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {<Card word={currentWord} {...{ markCorrect, markIncorrect }} />}
      </main>
    </Container>
  )
}

export default Home
